### ISSUE TITLE
How do events actually work?

### ISSUE THREAD

**Issue by SamusAranX** [rnine/SimplyCoreAudio#19]
The documentation is just a very barebones explanation of methods and classes, with nothing in it to explain how everything actually works.

By messing around, I managed to do this:
```swift
class ViewController: NSViewController, EventSubscriber {

	func eventReceiver(_ event: Event) {
		if let ahEvent = event as? AudioHardwareEvent {
			print(ahEvent)
		}
	}

	override func viewDidLoad() {
		super.viewDidLoad()

		NotificationCenter.defaultCenter.subscribe(self, eventType: AudioHardwareEvent.self, dispatchQueue: DispatchQueue.global(qos: .background))
	}

}
```

But as far as I can tell, there's no straightforward way to find out which AudioHardware event was actually called. How can I do that?

**Comment by rnine** [comment]
Documentation is barebones indeed. For now, please check the demo project, specifically: https://github.com/rnine/AMCoreAudio/blob/1e8672b466b3c38e105a5b0e606ddbadad15af50/AMCoreAudio%20Demo/AMCoreAudio%20Demo/ViewController.swift#L478-L581

**Comment by rnine** [comment]
Usage now documented in README.md
